# Generated by Django 5.1.4 on 2025-04-16 08:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('number_of_seats', models.IntegerField()),
                ('is_available', models.SmallIntegerField(choices=[(0, 'Reserved'), (1, 'Available')], default=1)),
                ('is_disable', models.SmallIntegerField(choices=[(0, 'Disable'), (1, 'Active')], default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2025, 4, 16, 8, 52, 42, 987492, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_available', models.SmallIntegerField(choices=[(0, 'Reserved'), (1, 'Available')], default=1)),
                ('is_disable', models.SmallIntegerField(choices=[(0, 'Disable'), (1, 'Active')], default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2025, 4, 16, 8, 52, 42, 986557, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='dashboard.classroom')),
            ],
        ),
    ]
