# Generated by Django 5.1.4 on 2025-05-02 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('number_of_seats', models.IntegerField()),
                ('is_available', models.SmallIntegerField(choices=[(0, 'Reserved'), (1, 'Available')], default=1)),
                ('is_disable', models.SmallIntegerField(choices=[(0, 'Disable'), (1, 'Active')], default=1)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_available', models.SmallIntegerField(choices=[(0, 'Reserved'), (1, 'Available')], default=1)),
                ('is_disable', models.SmallIntegerField(choices=[(0, 'Disable'), (1, 'Active')], default=1)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='dashboard.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[(0, 'Active'), (1, 'Completed'), (2, 'Cancelled')], default=0, max_length=20)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserved_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dashboard.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dashboard.seat')),
            ],
        ),
    ]
