# Generated by Django 5.1.4 on 2025-04-15 07:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='dashboard.classroom'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 7, 35, 46, 75596, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 7, 35, 46, 72093, tzinfo=datetime.timezone.utc)),
        ),
    ]
