# Generated by Django 5.1.4 on 2025-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='has_outlet',
            field=models.BooleanField(default=False),
        ),
    ]
