# Generated by Django 5.1.4 on 2025-04-15 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seat_classroom_seat_seat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 7, 36, 32, 294842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 7, 36, 32, 293843, tzinfo=datetime.timezone.utc)),
        ),
    ]
