# Generated by Django 5.1.4 on 2025-04-16 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_classroom_create_at_alter_seat_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 9, 3, 5, 421003, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 9, 3, 5, 421003, tzinfo=datetime.timezone.utc)),
        ),
    ]
