# Generated by Django 5.1.4 on 2025-05-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seat_has_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='has_outlet',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
    ]
