# Generated by Django 5.0 on 2025-05-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_seat_has_outlet"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "Active"),
                    (1, "Completed"),
                    (2, "Cancelled"),
                    (3, "Checked-In"),
                ],
                default=0,
                max_length=20,
            ),
        ),
    ]
