# Generated by Django 5.1.4 on 2025-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_reservation_checked_in_at_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationResetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_time', models.TimeField(help_text="When (each day) to reset today's reservations to Active")),
            ],
        ),
    ]
