# Generated by Django 5.1.4 on 2025-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_reservationresetsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_booking_duration', models.PositiveSmallIntegerField(default=4)),
                ('reset_time', models.TimeField(help_text="When (each day) to reset today's reservations to Active")),
            ],
        ),
        migrations.DeleteModel(
            name='ReservationResetSetting',
        ),
    ]
