# Generated by Django 5.1.4 on 2025-05-21 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_reservationsetting_delete_reservationresetsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationsetting',
            name='reset_time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(0, 'Active'), (1, 'Completed'), (2, 'Cancelled')], default=0, max_length=20),
        ),
    ]
