# Generated by Django 5.1.4 on 2025-05-22 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_reservation_checked_in_at_alter_seat_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
