# Generated by Django 5.0 on 2025-04-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverificationtoken'),
    ]

    operations = [
    ]
